[package]
name = "nativefier_tauri"
description = "Turn any web page into a desktop app (but, lightweight <1MB)"
version = "0.2.1"
edition = "2021"
license = "MIT"

[dependencies]
home = "0.5.4"
base64 = "0.20.0"
clap = { version = "4.1.1", features = ["derive"]}
