[package]
name = "web2app"
description = "Turn any web page into a desktop app (but, lightweight ~3MB)"
version = "0.2.12"
edition = "2021"
license = "MIT"

[dependencies]
home = "0.5.4"
base64 = "0.20.0"
clap = { version = "4.1.1", features = ["derive"]}
